env:
  global:
    - VERSION=0.${TRAVIS_BUILD_NUMBER}
  matrix:
    - ARCH=amd64
      OS=linux
      DOCKER_BUILD=gini/trello-dashboard:${VERSION}
      DOCKERFILE=Dockerfile.amd64
#    - ARCH=arm
#      OS=linux
#      DOCKER_BUILD=gini/trello-dashboard:rpi-${VERSION}
#      DOCKERFILE=Dockerfile.rpi

sudo: required

services:
  - docker

language: go
go:
  - 1.9.x

before_install:
  - go version
  - go get github.com/Sirupsen/logrus
  - go get github.com/VojtechVitek/go-trello
  - go get github.com/TV4/graceful

script:
  - CGO_ENABLED=0 GOOS=$OS GOARCH=$ARCH go build -v -o "trello-dashboard_$OS-$ARCH" -i -a .
#  - docker run --rm --reset
#  # prepare qemu
#  - 'if [ ${ARCH} = "arm" ]; then
#      docker run --rm --privileged multiarch/qemu-user-static:register --reset
#    fi'
  - docker build -t ${DOCKER_BUILD} -f ${DOCKERFILE} .
  - echo "Testing the docker image built..."
  - echo $(docker run ${DOCKER_BUILD} 2>&1)
  - if [[ "$(docker run ${DOCKER_BUILD} 2>&1)" == *"port number"* ]] ; then echo "Binary OK!" && exit 0 ; else echo "Binary not OK!" && exit -1 ; fi 
  # Publish on docker hub
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push ${DOCKER_BUILD}

branches:
  only:
    - master
